name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Ejecución de pruebas unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest moto boto3

      - name: Ejecutar pruebas con pytest
        run: PYTHONPATH=$(pwd) pytest .

  deploy:
    name: Despliegue automático en AWS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Verificar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

     # Despliegue con Zappa del módulo scraper
      - name: Deploy scraper with Zappa
        run: |
          source env/bin/activate
          cd punto1
          zappa update devInfo

      - name: deploy parser Zappa status
        run: |
          source env/bin/activate
          cd punto
          zappa status dev_csv

      # Despliegue con Zappa del módulo parser
      - name: Deploy parser with Zappa
        run: |
          source env/bin/activate
          cd punto3
          zappa update crawler

