name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    name: Revisión de código (flake8)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar flake8
        run: pip install flake8
      - name: Ejecutar flake8
        run: flake8 .

  test:
    name: Ejecutar pruebas unitarias (pytest)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar pruebas
        run: pytest

  deploy:
    name: Despliegue automático en AWS
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v3
    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Verificar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1
    - name: Desplegar lambda
      run: |
        # Crear y activar el entorno virtual
        python -m venv venv
        source venv/bin/activate
        
        # Instalar Zappa y boto3
        pip install zappa boto3
        
        # Desplegar Lambda de Scraping
        zappa update dev --settings_file Scrapper/zappa_settings.json
        
        # Desplegar Lambda de Procesamiento
        zappa update dev --settings_file Parser/zappa_settings.json
